apiVersion: v1
kind: Namespace
metadata:
  name: demo1
  annotations:
    "mission-control/playbook": kustomize-create-namespace
    "mission-control/run": 0191dc3f-209c-9f63-eb88-e62d2f469097
    "mission-control/createdBy": Admin