---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mission-control-argocd
  namespace: default
spec:
  chart:
    spec:
      chart: mission-control-argocd
      interval: 1m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flanksource
        namespace: default
  interval: 5m
  values: {}
