apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mission-control-kubernetes
  namespace: default
spec:
  chart:
    spec:
      chart: mission-control-kubernetes
      interval: 1m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flanksource
        namespace: default
  interval: 5m
  values:
    prometheus:
      url: http://kube-prometheus-stack-prometheus.monitoring:9090
