apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: log-component-status
  namespace: default
spec:
  title: Post pod status to HTTP Endpoint
  description: Post kubernetes pod component name and status to httpbin
  components:
    - types: 
      - Kubernetes::Pod
  actions:
    - name: Post data to httpbin
      http:
        url: https://httpbin.demo.aws.flanksource.com/post
        method: POST
        body: |
          {
            "component": {
              "name": "{{.component.name}}",
              "status": "{{.component.status}}"
            }
          }
        templateBody: true
        headers:
          - name: Content-Type
            value: application/json 

