## Component scraping etcd
kubeEtcd:
  enabled: true

##  Use either CoreDNS or kubeDns
coreDns:
  enabled: true

kubeDns:
  enabled: false

## Component scraping kube state metrics
kubeStateMetrics:
  enabled: true

## Configuration for kube-state-metrics subchart
##
kube-state-metrics:
  selfMonitor:
    enabled: true

## Component scraping the kube api server
kubeApiServer:
  enabled: true

## Component scraping the kube controller manager
kubeControllerManager:
  enabled: false

## Component scraping the kubelet and kubelet-hosted cAdvisor
kubelet:
  enabled: true
  serviceMonitor:
    # From kubernetes 1.18, /metrics/resource/v1alpha1 renamed to /metrics/resource
    resourcePath: "/metrics/resource/"

## Deploy node exporter as a daemonset to all nodes
nodeExporter:
  enabled: true
  service:
    port: 9200
