apiVersion: v
kind: Namespace
metadata:
  name: podinfo1
  annotations:
    "mission-control/playbook": provision-namespace-gitops
    "mission-control/run": 01918918-b001-7e37-284b-1a1c5d3d6619
    "mission-control/createdBy": System