apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
  annotations:
    config.kubernetes.io/origin: |
      path: cluster/namespaces/default/podinfo.yaml
spec:
  interval: 10m
  chart:
    spec:
      chart: podinfo
      version: 6.7.0
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: podinfo
      reconcileStrategy: ChartVersion
  values:
    resources:
      limits:
        cpu: 1000m
        memory: 3Gi
      requests:
        cpu: 1000m
        memory: 3Gi
